#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "小娟",
                "quest_type":           "杀",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "破烂的粉红布衫",
                "quest_type":           "寻",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "蓝衣家丁",
                "quest_type":           "杀",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "七星锤",
                "quest_type":           "寻",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "园工",
                "quest_type":           "杀",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "长剪",
                "quest_type":           "寻",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "小羊羔",
                "quest_type":           "杀",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "许廉龙",
                "quest_type":           "杀",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "灰布道袍",
                "quest_type":           "寻",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "青锋剑",
                "quest_type":           "寻",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "绿豆苗",
                "quest_type":           "寻",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "豌豆",
                "quest_type":           "寻",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "青豆",
                "quest_type":           "寻",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "韭菜",
                "quest_type":           "寻",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "大白菜",
                "quest_type":           "寻",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "大青菜",
                "quest_type":           "寻",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "小青菜",
                "quest_type":           "寻",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "小白菜",
                "quest_type":           "寻",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "白玉小马桶",
                "quest_type":           "寻",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "马鬃木刷",
                "quest_type":           "寻",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "蜜蜂",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "黄金",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "乞丐",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "疯狗",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "旧书",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "舍利子",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "护寺藏尼",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "一环禅杖",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "阴经",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "阳经",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "驼背老汉",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "草鞋",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "蓑衣",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "登徒子",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "竹剑",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "刨花油",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "油油的纸",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "鸡肉包",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "鸭油包",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "红色的细针",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "绿色的细针",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "黄色的细针",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "白色的细针",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "黑色的细针",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "朝拜的和尚",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "扫地的和尚",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "烧饭的和尚",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "挑水的和尚",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "砍柴的和尚",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "淘米的和尚",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "打杂的和尚",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "念经的和尚",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "粗布僧鞋",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "棉布僧鞋",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "蓝布僧鞋",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "洗得发白的僧鞋",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "青布僧鞋",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "紫布僧鞋",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "黑布僧鞋",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "白布僧鞋",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "粗布僧衣",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "棉布僧衣",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "蓝布僧衣",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "洗得发白的僧衣",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "青布僧衣",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "紫布僧衣",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "黑布僧衣",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "白布僧衣",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "风静",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "水手",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "花匠",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "老汉",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "赵国泰",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "园工剪",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "小园工",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "老农",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "镰刀",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "老者",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "烟斗",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "沉香镇的地头蛇",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "挑山夫",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "粗木扁担",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "忏悔徒",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "雅芳",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "伙计",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "黑色劲装",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "裸体女人",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "风骚雅人",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "年青人",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "丧尽天良的畜生",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "丫环",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "彩裙",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "小兜兜",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "小西门",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "女佣人",
                "quest_type":           "杀",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "青衣家丁",
                "quest_type":           "杀",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "六角锤",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "鸡毛",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "采花妞",
                "quest_type":           "杀",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "紫花瓣儿",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "紫衣家丁",
                "quest_type":           "杀",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "八楞玄铁锤",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "銮鱼衡冰",
                "quest_type":           "寻",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "过招要旨",
                "quest_type":           "寻",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "大辫子姑娘",
                "quest_type":           "杀",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "登山者",
                "quest_type":           "杀",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "采菱女",
                "quest_type":           "杀",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "壁虎",
                "quest_type":           "杀",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "小猫咪",
                "quest_type":           "杀",
                "exp_bonus":            20,
        ]),
});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

