#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "收破烂的",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "钱",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "钱",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "钱",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "钱",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "钱",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "樵夫",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "铁斧",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "乞丐",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "旧书",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "金鸡鸡",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "虾",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "鱼",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "护心镜",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":               HIC "无影神针" NOR,
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "野鸭",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "雷火珠",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "响尾蛇",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "玉发簪",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "竹刀",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "竹剑",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "三清道术",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "「轻功入门」",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "「内功简介」",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "「拳法入门」",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "「剑术简介」",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "「拆招秘决」",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "「闪躲之术」",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "「拳法入门」",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "皮鞭",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "木棍",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "单刀",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "铁锤",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "驼背老人",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "磨菜刀的",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "穿开裆裤的小孩儿",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "卖鱼的",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "买鱼的小姑娘",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "农家女",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "鸡毛毽子",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "农夫",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "农具店老板",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "阿发",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "胡英",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "老裁缝",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "土娼",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "卖菜的",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "大胖子",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "卖玩具的",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "卖药的",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "王仁德",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "店小二",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "老板娘",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "张铁匠",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "上了年纪的老太婆",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "茶博士",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "龙小云",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "油辣猪排",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "鱼香肉丝",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "纸花",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "纸钱",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "猪头",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "椒盐排骨",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "千金小姐",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "银簪",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "轻罗绸衫",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),

});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

