#include <ansi.h>
mapping *quest = ({
        ([      "quest":                "人皮酒袋",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "烤山猪肉",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "大老鼠",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "蚂蚁",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "蛐蛐",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "长剑",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "信鸽",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "黑牡丹",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "蓝天鹅",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "紫罗兰",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "红枚瑰",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "白茶花",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "黄玫瑰",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "孤独美",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "古形剑",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "铜哨",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "燕子",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "花蝴蝶",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "乌铁禅杖",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "木禅杖",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "破剑",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "破弯刀",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "舍利子",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "玉戒指",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "烤羊腿",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "蛇药",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "羊皮酒袋",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "恶魔亡魂",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":               HIC "鬼牙玄冥杖" NOR,
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "冰心诀",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "忘魂花",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":               HIG "忘魂果" NOR,
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "九条",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "九万",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "九桶",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "紫菁玉蓉膏",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":               HIR "断肠草" NOR,
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "紫金葫芦",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "残破古画",
                "quest_type":           "寻",
                "exp_bonus":            35,
        ]),
        ([      "quest":               CYN "豹牙手环" NOR,
                "quest_type":           "寻",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "大箱子",
                "quest_type":           "寻",
                "exp_bonus":            25,
        ]),
        ([      "quest":               "雪蛤蟆" ,
                "quest_type":           "寻",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "藏香",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":               "茶砖" ,
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":               "胡刀" ,
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "玉珠花" ,
                "quest_type":           "寻",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "玉戒指",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":               "玉手镯" ,
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                 "麻雀" ,
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                 "松鼠" ,
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "老妇人",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "饭篮",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        
        ([      "quest":                "竹筷子",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "粗米饭",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "铁剑",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "砍柴斧",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "竹筐",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "饭篮",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        
        ([      "quest":                "铁盒",
                "quest_type":           "寻",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "锄头",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "钉钯",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "大铁锤",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "镰刀",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "「三才剑谱」",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "卖面的老人",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "南宫十三",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "中药店老板",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "北芪",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "镰刀",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "砍林刀",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "糙面",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "党参",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "淮山",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "鲜鱼",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "韭菜合子",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "鸡毛毽子",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "开裆裤",
                "quest_type":           "寻",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "当归",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "黑瓷药瓮",
                "quest_type":           "寻",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "小面馆的地契",
                "quest_type":           "寻",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "古玉牌",
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "罗刹牌",
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "上茶的道士",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "扫地的道士",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "烧饭的道士",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "挑水的道士",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "砍柴的道士",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "淘米的道士",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "小竹拂尘",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "纯金叶子",
                "quest_type":           "寻",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "面目空白的木像",
                "quest_type":           "寻",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "茶花",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "九截鞭",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "大蟑螂",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "素菜包",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "生煎包",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "小笼包",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "大青菜",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "单刀",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "火炮丸",
                "quest_type":           "寻",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "黑牡丹" ,
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":               "「嘉德文选」",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "「九韬」",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "「太公辩」",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "「梁父文集」",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "「说律」",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "「古文志」",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "「乡书」",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "「佾风斋诗集」",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "内功心法",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "符咒入门",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "轻功入门",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "魔法简介",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "玉蒲团",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "金瓶梅",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "青瓷大碗",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "脆皮草鱼",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "陈皮大虾",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "川味肝片",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "狗皮膏药",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "子母双环",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "芙蓉鳝片",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "虎骨丸",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "高丽香蕉",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "橄榄鱼翅",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "果汁鱼球",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "花粉袋",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "货票",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "红油鸡片",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "玉簪",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "玉花",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "玉指",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "玉镯",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "锦绣鱼丝",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "椒盐面筋",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "云南白药",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "杀手牌",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                HIR "杀手剑" NOR,
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "飞刀",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "卤味儿",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "泥人儿",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "胡萝卜",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "牛头",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "大酒袋",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "人皮面具",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "风云赞歌",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "皱皱的破纸片",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "蚧味鱼米",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "清炒鳝糊",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "清炒虾仁",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "煮熟了的蛆",
                "quest_type":           "寻",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "乳香鲳鱼",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "茅山道术入门",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "大风丸",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "牛皮盾",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "生烧青鱼",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "生烧扒翅",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "白毛巾",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "小风车",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "小炒粉丝",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "罗卜条",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "羊头",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "银巢红珠",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "大黑石",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "风清",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "小金刚经",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "大金刚经",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "涅般经",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "大乘经",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "小乘经",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "铜佛钟",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "铜佛鼓",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "古松琴",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "七彩丝缎带",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "火巨灵",
                "quest_type":           "杀",
                "exp_bonus":            45,
        ]),
        ([      "quest":                HIR "火焰长刀" NOR,
                "quest_type":           "寻",
                "exp_bonus":            65,
        ]),
        ([      "quest":                "萤火虫",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "黑玉发簪",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "大雁",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "勿忘我",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "昭红",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "软红",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "石榴裙",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "卜亚男",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "良家妇女",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "带血纱衣",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "残破的女子内衣",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "家奴",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "家奴短褂",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "草玉璧",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "古玉牌",
                "quest_type":           "寻",
                "exp_bonus":            95,
        ]),
        ([      "quest":                "小金杯",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "酒玉璧",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "柳玉璧",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "女玉璧",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "嫩藕",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "水玉璧",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "雪玉璧",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "嫩藕",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "大棉袄",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "李霞",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "卤蛋",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "罗刹牌",
                "quest_type":           "寻",
                "exp_bonus":            95,
        ]),
        ([      "quest":                "鹿茸",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "精钢园桶",
                "quest_type":           "寻",
                "exp_bonus":            95,
        ]),
        ([      "quest":                "野人参",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "血肠",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "玄苏剑",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "丝绸马褂",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "吹雪残云巾",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "吹雪残云衣",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "吹雪残云靴",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "吹雪残云带",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "梅木长凳",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "麻绳",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "干木柴",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "半干的血滴",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "小木筏",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "路边的野花",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "枯黄的叶",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "梅树幼苗",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "半干的木柴",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "人影",
                "quest_type":           "杀",
                "exp_bonus":            15,
        ]),
});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

