#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "厨子",
                "quest_type":           "杀",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "碧玉刀",
                "quest_type":           "寻",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "护寺藏尼",
                "quest_type":           "杀",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "大红尼袍",
                "quest_type":           "寻",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "大绵羊",
                "quest_type":           "杀",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "驼背老人",
                "quest_type":           "杀",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "小翠",
                "quest_type":           "杀",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "绣花鞋",
                "quest_type":           "寻",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "粉红衫",
                "quest_type":           "寻",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "细梅剑",
                "quest_type":           "寻",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "道士",
                "quest_type":           "杀",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "孙天灭",
                "quest_type":           "杀",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "谢长勤",
                "quest_type":           "杀",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "宋长清",
                "quest_type":           "杀",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "金护卫",
                "quest_type":           "杀",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "大厨",
                "quest_type":           "杀",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "卤味儿",
                "quest_type":           "寻",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "雅公子",
                "quest_type":           "杀",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "摺扇",
                "quest_type":           "寻",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "俏鸨母",
                "quest_type":           "杀",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "舞蝶彩衫",
                "quest_type":           "寻",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "关东大汉",
                "quest_type":           "杀",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "血肠",
                "quest_type":           "寻",
                "exp_bonus":            35,
        ]),

});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

