#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "珠宝商",
                "quest_type":           "杀",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "碧玉胡刀",
                "quest_type":           "寻",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "云卒",
                "quest_type":           "杀",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "风兵",
                "quest_type":           "杀",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "风云战甲",
                "quest_type":           "寻",
                "exp_bonus":            75,
        ]),
        ([      "quest":                HIR "红缨" NOR + "长枪" NOR,
                "quest_type":           "寻",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "荆无命",
                "quest_type":           "杀",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "参机大师",
                "quest_type":           "杀",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "烈火孽龙",
                "quest_type":           "杀",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "镜魂",
                "quest_type":           "杀",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "天缺古月寒",
                "quest_type":           "寻",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "胸襟半开的轻纱丝袍",
                "quest_type":           "寻",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "姬冰雁",
                "quest_type":           "杀",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "蓝小云",
                "quest_type":           "杀",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "溅满血的黑布袍",
                "quest_type":           "寻",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "诸葛十一",
                "quest_type":           "杀",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "小豆豆",
                "quest_type":           "杀",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "管零",
                "quest_type":           "杀",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "张剑",
                "quest_type":           "杀",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "蝠王",
                "quest_type":           "杀",
                "exp_bonus":            75,
        ]),


});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

