#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "淳于怀太",
                "quest_type":           "杀",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "蛇鳞皮鞭",
                "quest_type":           "寻",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "叶灵",
                "quest_type":           "杀",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "红衣",
                "quest_type":           "寻",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "叶雪",
                "quest_type":           "杀",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "狗郎君",
                "quest_type":           "杀",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "黄衣人",
                "quest_type":           "杀",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "小兰",
                "quest_type":           "杀",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "毒龙沙",
                "quest_type":           "寻",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "牡丹",
                "quest_type":           "杀",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "冬青",
                "quest_type":           "杀",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "玫瑰",
                "quest_type":           "杀",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "杜鹃",
                "quest_type":           "杀",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "白袍妇",
                "quest_type":           "杀",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "李长慎",
                "quest_type":           "杀",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "灰布道袍",
                "quest_type":           "寻",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "供香",
                "quest_type":           "寻",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "太极拳练功图",
                "quest_type":           "寻",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "落第书生",
                "quest_type":           "寻",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "抓破美人脸",
                "quest_type":           "寻",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "白颈灰熊",
                "quest_type":           "杀",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "锡护卫",
                "quest_type":           "杀",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "查猛",
                "quest_type":           "杀",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "黄衣卫",
                "quest_type":           "杀",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "金钱袍",
                "quest_type":           "寻",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "芳儿",
                "quest_type":           "杀",
                "exp_bonus":            40,
        ]),
        ([      "quest":               HIY "五" + HIR "彩" NOR + "紧身裙",
                "quest_type":           "寻",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "大胡子",
                "quest_type":           "杀",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "老实和尚",
                "quest_type":           "杀",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "狂嫖客",
                "quest_type":           "杀",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "团金褂",
                "quest_type":           "寻",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "大胡子豪客",
                "quest_type":           "杀",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "李神童",
                "quest_type":           "杀",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "老山羊",
                "quest_type":           "杀",
                "exp_bonus":            40,
        ]),

});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

