#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "老刀把子",
                "quest_type":           "杀",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "青木剑",
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "竹笠",
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "灰袍",
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "箫王孙",
                "quest_type":           "杀",
                "exp_bonus":            100,
        ]),
        ([      "quest":               HIM "天蚕丝带" NOR,
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":               HIW "白虎之铠" NOR,
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":               HIC "青龙宝甲" NOR,
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":               HIR "魅影神靴" NOR,
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "蓝天锤",
                "quest_type":           "杀",
                "exp_bonus":            100,
        ]),
        ([      "quest":               HIG "毁天锤" NOR,
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":               BLU "蓝布衣" NOR,
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "垓下刀",
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "铁少",
                "quest_type":           "杀",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "虞姬剑",
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "雪蕊儿",
                "quest_type":           "杀",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "粗布白袍",
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "粗布鹅黄袍",
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "丁乘风",
                "quest_type":           "杀",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "七星翻云靴",
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "三清神冠",
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "天师道袍",
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "咒剑王夫",
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "璺剑王夫",
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "九星翻云靴",
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "六根清冠",
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "地旗道袍",
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "账房先生",
                "quest_type":           "杀",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "上官金虹",
                "quest_type":           "杀",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "吴青",
                "quest_type":           "杀",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "金钱袍",
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "龙凤双环",
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "阿飞",
                "quest_type":           "杀",
                "exp_bonus":            100,
        ]),
        ([      "quest":                 HIR "绑着一块木头的锈铁片" NOR,
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "西门吹雪",
                "quest_type":           "杀",
                "exp_bonus":            100,
        ]),
        ([      "quest":                 HIR "寒天吹血" NOR,
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":                 "寒天冰衣" ,
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "满脸风霜的老人",
                "quest_type":           "杀",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "陆小凤",
                "quest_type":           "杀",
                "exp_bonus":            100,
        ]),
});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

